### PR TITLE
Allow P2 jobs

### PR DESCRIPTION
**Pull request by ryancouto**
Respect max priority of P2

### CODE REVIEW

**Comment by dgdonut** [comment]
Seems fine, but where are we going with this? Is there an internal ticket with approach we are taking?

**Comment by ryancouto** [comment]
This was just an oversight when we deployed changes using P2 jobs last week

**Review by dgdonut — APPROVED** [review]

**Review by JeanetteBruno — APPROVED** [review]
Recommend we have a MaxPriority constant in stateful_scheduler.go, to avoid having to remember to change in multiple places in the future

**Comment by dgdonut** [comment]
^ oh, nice

**Comment by ryancouto** [comment]
@JeanetteBruno good call will do

**Pull request merged**
