### PR TITLE
Remove worker binary config files

### PR DESCRIPTION
**Pull request by cheyenne-martinez**

### CODE REVIEW

**Review by dgdonut — DISMISSED** [review]
LGTM - not sure what the problem with ci is, make ci passed for me locally. It may just be stuck waiting for resources.

**Comment by harshita-chaudhary** [comment]
I noticed that deleting binaries/workerserver dir is causing this, don't know why.

**Comment by dgdonut** [comment]
Yeah, I think we broke a bunch of things in #548 actually. Because we still had a binaries/workerserver dir in that branch, everything worked, because a bunch of things actually depend on "workerserver". In this diff we renamed workerserver to worker, which is going to cause issues. We're going to need to preserve the "workerserver" binary name, because we rely on a bunch of ps commands to deal with that binary, and "worker" is way too generic and likely most machines have dozens of procs running as the name "worker"

**Comment by dgdonut** [comment]
I opened #549 and it looks like CI is passing there, recommend we merge that and then update this PR based on that.

**Comment by harshita-chaudhary** [comment]
Makes sense, I also have lots of files being added/changed under worker. Will merge after Cheyenne's PR. Thanks for fixing this issue.

**Comment by cheyenne-martinez** [comment]
Ok I'll update this with changes from [#549](https://github.com/twitter/scoot/pull/549)

**Review by dgdonut — APPROVED** [review]
there we go

**Pull request merged**
