### PR TITLE
runner: Use *int for exitCode in runner.RunStatus

### PR DESCRIPTION
**Pull request by ryancouto**
We got rid of DeadLetterExitCode with e395c1af3aca2f7dd298545533baccc0ff26afd1. The intent was that for tasks that were unable to run, we wouldn't return an exit code. RunStatus's exit code is of type int, which meant when there was no exit code provided, it initialized to a zero value. Changing to an *int allows for nil exit codes.

### CODE REVIEW

**Comment by dgdonut** [comment]
What do we get for supporting nil in these codes? API clients like Sickle should just be ignoring ExitCode unless status is COMPLETE, I thought.

**Review by JeanetteBruno — APPROVED** [review]
Assuming this change is to be able to differentiate between nil exit code and 0?

Would be nice to provide the description for the worker's QueryWorker() api method explain the semantics of the fields in the WorkerStatus structure.  (Note: I took a look at the public go docs - they were not useful)

**Review by jasonbs10 — COMMENTED** [review]
I'd table this PR unless it's fixing a specific issue. My preference is to revisit the API holistically when Drew makes changes to support remoting.

**Comment by ryancouto** [comment]
It is fixing a specific issue (DX-2512) - though one that could be solved differently (as @dgassaway  described) without any modifications to OSS

**Pull request closed without merging**
