### PR TITLE
Update to go 1.12.7 and module-based dependencies

### PR DESCRIPTION
**Pull request by dgdonut**
The intention of this is twofold:
* Bump to a more modern golang version and use the language's supported dep management workflow
* Make the user and developer workflows for scoot easier. This should make it easier to get scoot up and running "out of the box" without worrying about arcane requirements (see https://github.com/twitter/scoot/issues/426), and make dep management for developers easier (as well as cleaning up some existing rough edges)

Reviewable but not in a rush - might let this simmer for a couple of weeks.

### CODE REVIEW

**Comment by ryancouto** [comment]
yesssss awesome. will take a closer look this weekend/next week.

**Comment by Abhik1998** [comment]
Hey is this the fix for the issue #426 ??

**Comment by dgdonut** [comment]
Yes.

**Review by JeanetteBruno — APPROVED** [review]
First - Thanks for deleting unused files!

do we need to check in generated files?

**Comment by dgdonut** [comment]
We should check in generated stuff, yes - it ensures consistency between users in case e.g. someone has a different local binary of the generating tool, or the generating tool pulls in new libraries when it's invoked, resulting in different code generated, etc. It also separates the "build & run" use case from the "develop" use case for this repo, and makes the former one easier.

**Pull request merged**
